const TEAM_COUNTRY_CODES: Record<string, string> = {
  ALG: "DZ",
  ARG: "AR",
  AUS: "AU",
  AUT: "AT",
  BEL: "BE",
  BFA: "BF",
  BOL: "BO",
  BRA: "BR",
  CAN: "CA",
  CHI: "CL",
  CHN: "CN",
  CIV: "CI",
  CMR: "CM",
  COL: "CO",
  CRC: "CR",
  CRO: "HR",
  CZE: "CZ",
  DEN: "DK",
  ECU: "EC",
  EGY: "EG",
  ENG: "GB-ENG",
  ESP: "ES",
  FIN: "FI",
  FRA: "FR",
  GER: "DE",
  GHA: "GH",
  GRE: "GR",
  HON: "HN",
  HUN: "HU",
  IDN: "ID",
  IRL: "IE",
  IRN: "IR",
  IRQ: "IQ",
  ISL: "IS",
  ITA: "IT",
  JAM: "JM",
  JOR: "JO",
  JPN: "JP",
  KEN: "KE",
  KOR: "KR",
  KUW: "KW",
  MAR: "MA",
  MEX: "MX",
  MLI: "ML",
  NED: "NL",
  NGA: "NG",
  NOR: "NO",
  NZL: "NZ",
  OMA: "OM",
  PAN: "PA",
  PAR: "PY",
  PER: "PE",
  POL: "PL",
  POR: "PT",
  QAT: "QA",
  ROU: "RO",
  RSA: "ZA",
  SAU: "SA",
  SCO: "GB-SCT",
  SEN: "SN",
  SRB: "RS",
  SUI: "CH",
  SWE: "SE",
  THA: "TH",
  TUN: "TN",
  TUR: "TR",
  UAE: "AE",
  UKR: "UA",
  URU: "UY",
  USA: "US",
  UZB: "UZ",
  VEN: "VE",
  VIE: "VN",
  WAL: "GB-WLS",
  ZAM: "ZM",
  ZIM: "ZW",
};

export function getCountryCode(tla?: string | null): string | null {
  if (!tla) return null;
  return TEAM_COUNTRY_CODES[tla.toUpperCase()] ?? null;
}

export function getFlagUrl(
  tla?: string | null,
  size: "w40" | "w80" = "w80"
): string {
  const code = getCountryCode(tla);
  if (!code) return "";
  return `https://flagcdn.com/${size}/${code.toLowerCase()}.png`;
}
